name: Deploy my_portfolio application

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.NEXT_PUBLIC_SERVICE_ID }}" >> .env && echo "SITE_URL=${{ secrets.NEXT_PUBLIC_TEMPLATE_ID }}" >> .env && echo "SITE_URL=${{ secrets.NEXT_PUBLIC_PUBLIC_KEY }}" >> .env
      - name: Build docker image
        run: docker build -t raselahmad/my_portfolio .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push raselahmad/my_portfolio:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull raselahmad/my_portfolio:latest
      - name: Delete old container
        run: docker rm -f my_portfolio_container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name my_portfolio_container raselahmad/my_portfolio 